### ISSUE TITLE
Split the Support Repo

### ISSUE THREAD

**Issue by justintadlock** [themehybrid/hybrid-support#2]
`/Support` should be split into separate `/Tools` and `/Contracts` repos.  This will follow the original architecture and maintain back-compat.

**Comment by lkraav** [comment]
After split, this repo would sunset?

**Comment by justintadlock** [comment]
Correct -- unless there's another reason for this particular repo.

**Comment by saas786** [comment]
I modelled this repo after: https://github.com/illuminate/support

So collect all support tools, interfaces, abstracts etc here, which doesn't directly fall under either main package, or addon modules, and can be utilized by main package and other addon modules, or even helpful for Theme / Plugin development.

**Comment by skyshab** [comment]
Why can't Tools and Contracts be included in the hybrid-core package?

**Comment by saas786** [comment]
> Why can't Tools and Contracts be included in the hybrid-core package?

This package is a free floating package, any dev can utilize this package (if needed), without either using hybrid-core or any other addon module.

There is no hard a fast rule here, it can be inside hybrid-core, each module can have its own Contracts & Tools etc.

This repo only follows the `illuminate` logic of collecting contracts, tools etc in support module / package.

If there is a solid point why it should be either separate packages for contracts & tools, or it should be a part of hybrid-core, I would like to keep them in this repo.

**Comment by skyshab** [comment]
Thanks for your explanation Syed. 

It looks like Laravel has a separate package for contracts. Support seems to correlate more to "tools". I think of all the above options, I tend to agree with Justin's suggestion to split this to contracts and tools.

**Comment by justintadlock** [comment]
> It looks like Laravel has a separate package for contracts. Support seems to correlate more to "tools". I think of all the above options, I tend to agree with Justin's suggestion to split this to contracts and tools.

This is correct, and it is how I modeled it originally.  The difference being that I prefered the term `Tools` over `Support` for this project.

`Contracts` should be its separate thing because someone could, theoretically, want to implement something of their own but use the contracts we already have.

**Comment by justintadlock** [comment]
Ported the repos over:

- https://github.com/themehybrid/hybrid-contracts
-  https://github.com/themehybrid/hybrid-tools

**Comment by skyshab** [comment]
@justintadlock So, the Contracts package contains contracts for all other Hybrid packages, which now need to be removed?
